version: '3.8'

services:
  wbic-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wbic-backend
    environment:
      - PORT=3000
      - NODE_ENV=production
      - SMTP_HOST=localhost
      - SMTP_PORT=25
      - SMTP_FROM=info@wbic.nl
      - CLOUDFLARE_TURNSTILE_SECRET=${CLOUDFLARE_TURNSTILE_SECRET}
    networks:
      - n8n_default
    restart: always
    expose:
      - 3000
    volumes:
      - ./backend/node_modules:/app/node_modules

networks:
  n8n_default:
    external: true
